### ISSUE TITLE
`vagrant up` crashes when `v.gui = false` (M1 Mac, Ventura, VMWare 13)

### ISSUE THREAD

**Issue by fredngo** [hashicorp/vagrant-vmware-desktop#53]
### Vagrant version

```
% vagrant -v
Vagrant 2.3.3
```

### Vagrant VMware plugin version

```
% vagrant plugin list
vagrant-vmware-desktop (3.0.1, global)
  - Version Constraint: > 0
```

### Vagrant VMware utility version

```
% /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility -v
1.0.21
```

### Host operating system

```
% sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

Also:

```
% arch
arm64
```

```
% vmrun
vmrun version 1.17.0 build-20802013
```

And:

```
VMware Fusion Player Version 13.0.0 (20802013)
```

### Guest operating system

```
config.vm.box = "starboard/ubuntu-arm64-20.04.5"
config.vm.box_version = "20221120.20.40.0"
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "starboard/ubuntu-arm64-20.04.5"
  config.vm.box_version = "20221120.20.40.0"

  config.vm.provider "vmware_desktop" do |v|
    v.gui = false
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
  end
end
```

### Debug output

[Gist with debug output](https://gist.github.com/fredngo/a051821b0c50f7956057731aea6e431c)

### Expected behavior

The machine should boot up without the GUI present and without complaint

### Actual behavior

```
% vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Checking if box 'starboard/ubuntu-arm64-20.04.5' version '20221120.20.40.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Volumes/VMs/Vagrant/machines/machines/default/vmware_desktop/07a03504-b2cd-4a80-b776-6ed8ed459672/ubuntu-arm64-20.04.5-3.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2022-11-26T16:18:09.859| ServiceImpl_Opener: PID 41624
Error: The operation was canceled

Stderr:
```

Please see detailed debug output in the Gist above.

### Steps to reproduce

1. Use the `Vagarantfile` provided above
2. Run `vagrant up`
3. Replacing `v.gui = false` with `v.gui = true` will cause the VM to finishing booting up, but with the GUI present (which is not desirable)

**Comment by ptrk8** [comment]
Just bumping this - wondering if you ever found a fix for this?

**Comment by jasper-s** [comment]
I'm having the same issue, following here...

**Comment by mikeroySoft** [comment]
> This will be resolved once we have universal binary builds worked out and released on the Vagrant side of things.

Is there a target ETA for universal binaries? 
My team and I would be happy to help... (I'm the PM for Fusion)

**Comment by ineseleuch** [comment]
Yes please love vagrant and it works amazingly with VMware so far quite happy with the perf and all so far the only thing annoying is you have to have the GUI there in the background. Following this can you please let us know about the ETA for this ? Thanks a lot

**Comment by chrisroberts** [comment]
Hi everybody!

Sorry for the delay on this. Building a universal Vagrant package was a bit complicated and it ended up getting combined with some build process updates and a major Ruby version upgrade. The good news is that it has been released and is [now available](https://developer.hashicorp.com/vagrant/downloads). Upgrading Vagrant will resolve this issue.

Cheers!

**Comment by chrisroberts** [comment]
@mikeroySoft Thank you for the offer! And my apologies for missing it. I was heads down, focusing on getting everything working and didn't see it :slightly_smiling_face:

**Comment by douglasawh** [comment]
I'm on 2.3.7 and still getting:
```

An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "fusion", "start", "/Users/dwhitfield0322/vagrant/vmware-test/.vagrant/machines/default/vmware_desktop/82705c21-0d7f-404d-9150-c114266961c9/Rocky-9-Vagrant-VMware-9.2-20230513.0.x86_64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2023-09-27T13:14:55.758| ServiceImpl_Opener: PID 5521
Error: The operation was canceled

Stderr: 
```

**Comment by grpanho** [comment]
Hey @chrisroberts, sorry to bother. I have already update but the issue still happens. Even if I set `gui = true`, the vm doesn't boot. Below is the error and the versions used, any ideia about why this is happening?

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "fusion", "start", "/Users/grpanho/Documents/CC/Redes_Avancadas/T2_SNMP/.vagrant/machines/snmp1/vmware_desktop/c3c3124e-52d8-46fb-bbd4-3db728c71b86/Rocky-9-Vagrant-VMware-9.2-20230513.0.x86_64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]
```

```
% vagrant -v
Vagrant 2.4.0
```
```
% /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility -v  
1.0.22
```
```
% sw_vers
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
```
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VMs = 1

Vagrant.configure("2") do |config|
  (1..VMs).each do |i|
   config.vm.define "snmp#{i}" do |config|
    config.vm.box = "rockylinux/9"
    config.vm.hostname = "snmp#{i}"

      config.vm.provider "vmware_desktop" do |v|
        v.gui = false
#        v.memory = "512"
#        v.cpus = "2"
      end
    end
   end
end
```

VMware Fusion version is 13.5.0.

**Comment by Haugen** [comment]
Having the same issue over here. VMware Fusion `13.5.0`, Vagrant `2.4.0`, vagrant-vmware-utility `1.0.21`. As long as I set `gui = true` in the Vagrantfile it works, but without it the box crashes on startup.

I have tried with both these boxes:
- `spox/ubuntu-arm`
- `bytesguy/ubuntu-server-20.04-arm64`

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "fusion", "start", "/Users/haugen/vms/test/.vagrant/machines/default/vmware_desktop/aa30091e-d77a-4b6e-a397-d85f9abaae5b/Ubuntu Server 20.04.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2023-11-20T18:37:50.038| ServiceImpl_Opener: PID 97584
Error: The operation was canceled

Stderr:
```

**Comment by Amasiani** [comment]
On my M1 it gave this error after  attempting to start the gui.
when I used the setting above.

Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
Vagrant timed out while trying to start the VMware machine. This
error is caused by VMware never successfully starting the machine.
This can often be fixed by simply retrying. If the error persists,
please verify that VMware is functional. This is not a Vagrant
issue.

**Comment by shayne008** [comment]
> On my M1 it gave this error after attempting to start the gui. when I used the setting above.
> 
> Bringing machine 'default' up with 'vmware_desktop' provider... ==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date... ==> default: Verifying vmnet devices are healthy... ==> default: Preparing network adapters... ==> default: Starting the VMware VM... Vagrant timed out while trying to start the VMware machine. This error is caused by VMware never successfully starting the machine. This can often be fixed by simply retrying. If the error persists, please verify that VMware is functional. This is not a Vagrant issue.

I am getting the same issue

**Comment by aayushsapkota9** [comment]
I got a workaround for this on Macbook m1. 
I was running the terminal through Rosetta 2 (which allows Intel-based applications to run on Apple Silicon), which was causing vagrant to download amd64 images. 
on running `uname -m` the output was `i386` so to fix that:

1. Go to finder
2. Go to Application
3. Go to Utilities
4. Right click **Terminal** or control + 
5. Click **Get info**
6. Uncheck Open usign Rosetta 

Restart the terminal and upon running `uname -m`  `uname -m` should appear. 

This fixed my issue hope it fixes yours too. 
<img width="272" alt="Screenshot 2024-07-25 at 14 38 45" src="https://github.com/user-attachments/assets/ce0f252f-f1c5-47c2-8ea1-e903e53a6848">

**Comment by harisai-m** [comment]
@aayushsapkota9 Mine is already arm64 but still getting the issue.
